# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVaaWknvFarYub-NyToNIP8BYudT-0uu
"""

def can_king_move(checkerboard, x1, y1, x2, y2):
    if checkerboard[x1][y1] != 1:
        return "No"

    if checkerboard[x2][y2] == 1:
        return "No"

    if abs(x2 - x1) <= 1 and abs(y2 - y1) <= 1 and (x1 != x2 or y1 != y2):
        return "Yes"

    return "No"

x1, y1 = map(int, input().split())
x2, y2 = map(int, input().split())

print(can_king_move(checkerboard, x1, y1, x2, y2))

